### ISSUE TITLE
Medicine registration certificate

### ISSUE THREAD

**Issue by jagoje** [openmsupply/conforma-server#703]

**Comment by jagoje** [comment]
Once a product registration application has been approved, a certificate should be generated.

The certificate template we have been provided is as follows:
https://docs.google.com/document/d/1j05WPEm4PP7j7cX4aoWI9cZ_beDb0RJaaqCfzwWobLA/edit

However, there are two parts that require free text entry from the evaluator. 

@nmadruga, please let me know your thoughts on how we may be able to input text from the evaluator within the conditions sections.

**Comment by jagoje** [comment]
@CarlosNZ  here is the certificate, I have done up in ODT :) 

[pt_certificate_of_product_registration (2) (1).odt](https://github.com/openmsupply/conforma-server/files/9041998/pt_certificate_of_product_registration.2.1.odt)

**Comment by CarlosNZ** [comment]
> @CarlosNZ here is the certificate, I have done up in ODT :)

Thanks, have put in Templates repo / Angola folder. Do you have access to that? Would be good to dump them in there as you go. Might be better to start using a Drive/Dropbox folder for this stuff -- what do you think?

**Comment by nmadruga** [comment]
Updating: most of the work is done and saved our drive on folder: `Correspondence templates/ProdRegistration`.
There is a few things missing, basically the lists aren't functional yet for: active ingredients, and all the manufacturers.

**Comment by nmadruga** [comment]
Today I'm committed to be finishing this one! It has been so long trying to fix this. It ended up the problem was this issue: openmsupply/conforma-web-app/issues/1327 which is comprehensive but took some time to figure out. 

And answering @CarlosNZ question in telegram: 
> is there any particular reason why you’re fetching most of the “data” properties from “outputCumulative” rather than “applicationData.responses”? Responses is easier to deal with — I generatlly only use outputCumulative as a last resort

The reason is just not to have 2 places to update in case we change any of those codes. I know that's a problem that we should not be renaming the codes, but sometimes it's needed and I though it was better to get straight from the new data_view created. With all that said, I'm still getting problems to access the `data` destructed object in the Carbone template. So I have changed to get straight from `data_view_product` which should also be accessible... Testing this now.

**Comment by nmadruga** [comment]
Ok... almost but not completely sorted out yet!

All the lists aren't showing correctly. I'll continue to investigate this today

**Comment by nmadruga** [comment]
Carls is on it YEY Looking almost ready

**Comment by nmadruga** [comment]
I'll test this one again today 👼
