### ISSUE TITLE
Resetting password has case issues causing error.

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/conforma-server#809]
I noticed that the case cleaning / case sensitivity of username inputs isn't working right when resetting passwords. The field only recognises real passwords, however it won't flag if the password has any cases wrong. This means a user can submit a password reset request and conforma will throw an error which the user wouldn't understand. It is also difficult for the user to identify what went wrong unless they are very aware of the case of their username.

![username case issue](https://user-images.githubusercontent.com/90807420/183787708-61cb02c0-235a-4581-83d2-21855b62441e.gif)

Possibly a minor issue. Affects UX when they get the case of their username wrong.

Also probably very easy to implement a case cleaning function for username inputs, or to make the initial validation case sensitive on the front end.

**Comment by CarlosNZ** [comment]
Interesting, good catch.

The `isUnique` endpoint that we check does do case-insensitive check. This is because we normally want to keep names unique, even with case differences. If there is a user (or company) called "john", we don't want anyone signing up with the name "John", for example. 

This is fine for user registration, but not so good in this case, as you've pointed out. The error must occur because of the action that runs on submit which looks up the user name and gets nothing back if the case is different to what's stored.

Couple of options:
- add a new parameter to "check-unique" endpoint: "caseSenstive: true/false" (default true, but we'd make it false in this case)
- make the GraphQL query that fetches the email case-insensitive (and maybe the modifyRecord one on completion)

I think the first option is more robust, as it wouldn't let the user think their username was correct if they got the case wrong.

But both options would require a tweak to the "passwordReset" templates.
